server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: ["http://elasticsearch:9200"]


monitoring.ui.container.elasticsearch.enabled: true
monitoring.ui.container.logstash.enabled: true

elasticsearch.username: kibana_system
elasticsearch.password: ${KIBANA_SYSTEM_PASSWORD}

xpack.encryptedSavedObjects.encryptionKey: BgpxXYcp6vYhn8kkV3gHMWDix+XinN887nxXR/5uceY=

xpack.fleet.agents.fleet_server.hosts: [ "http://fleet-server:8220" ]

xpack.fleet.outputs:
  - id: fleet-default-output
    name: default
    type: elasticsearch
    hosts: [ "http://elasticsearch:9200" ]
    is_default: true
    is_default_monitoring: true

xpack.fleet.packages:
  - name: fleet_server
    version: latest
  - name: system
    version: latest
  - name: elastic_agent
    version: latest
  - name: docker
    version: latest
  - name: apm
    version: latest

xpack.fleet.agentPolicies:
  - name: Fleet Server Policy
    id: fleet-server-policy
    description: Static agent policy for Fleet Server
    monitoring_enabled:
      - logs
      - metrics
    package_policies:
      - name: fleet_server-1
        package:
          name: fleet_server
      - name: system-1
        package:
          name: system
      - name: elastic_agent-1
        package:
          name: elastic_agent
      - name: docker-1
        package:
          name: docker
  - name: Agent Policy APM Server
    id: agent-policy-apm-server
    description: Static agent policy for the APM Server integration
    monitoring_enabled:
      - logs
      - metrics
    package_policies:
      - name: system-2
        package:
          name: system
      - name: elastic_agent-2
        package:
          name: elastic_agent
      - name: apm-1
        package:
          name: apm
        inputs:
          - type: apm
            vars:
              - name: host
                type: text
                value: 0.0.0.0:8200
              - name: url
                type: text
                value: http://apm-server:8200
